#配置数据库连接的相关信息
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wangjf?serverTimezone=UTC
      username: root
      password: wang1997
#注册PageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
#设置myBatis日志
logging:
  level:
    #Mapper所在的包
    com.wangjf.dao: debug

